baseURL = 'https://matthiasforster.github.io/'
languageCode = 'en-us'
title = 'Wiser for KNX Apps'
theme = "hugo-book"
[params]
    # Setze dies auf true, wenn du KEINE menu/index.md nutzen willst
    BookSection = "/"
[markup]
  [markup.highlight]
    style = "emacs"  # pygments emacs
    lineNos = true
    noClasses = true
